version: '3.8'
services:
  web:
    build: .
    environment:
      - TZ=Europe/Moscow
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000-8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_compas
      - POSTGRES_PASSWORD=compas
      - POSTGRES_DB=django_compas_db
  redis:
    image: redis:alpine

volumes:
  postgres_data:
